### ISSUE TITLE
Test alternative icon integration.

### ISSUE THREAD

**Issue by UrielCh** [J053Fabi0/Ayn-Rand-Frases-Bot-Telegram#7]
Hi there is 2 way to integrate my icon set, can you please check the size of the project now.

the replace in import_map.json
```ts
    "react-icons/ai": "https://cdn.jsdelivr.net/gh/urielch/react-icons-ai@1.0.8/mod.ts",
    "react-icons/bs": "https://cdn.jsdelivr.net/gh/urielch/react-icons-bs@1.0.8/mod.ts",
    "react-icons/fi": "https://cdn.jsdelivr.net/gh/urielch/react-icons-fi@1.0.8/mod.ts",
```
by 
```ts
    "react-icons/ai/": "https://cdn.jsdelivr.net/gh/urielch/react-icons-ai@1.0.8/icon/",
    "react-icons/bs/": "https://cdn.jsdelivr.net/gh/urielch/react-icons-bs@1.0.8/icon/",
    "react-icons/fi/": "https://cdn.jsdelivr.net/gh/urielch/react-icons-fi@1.0.8/icon/",
```

then 

```ts
export { FiTrash2 } from "react-icons/fi";
export { AiFillEdit, AiOutlineSearch } from "react-icons/ai";
export { BsCaretLeftFill, BsCaretRightFill, BsSearch } from "react-icons/bs";
```
by
```ts
export FiTrash2 from "react-icons/fi/FiTrash2.ts";
export AiFillEdit from "react-icons/ai/AiFillEdit.ts";
export AiOutlineSearch  from "react-icons/ai/AiOutlineSearch.ts";
... same change for  BsCaretLeftFill, BsCaretRightFill, BsSearch } from "react-icons/bs";
```
then check the size of the project after the change.

**Comment by J053Fabi0** [comment]
Great! Thank you for taking the time to craft this suggestion.

# Problems importing

```json
"react-icons-ai/": "https://cdn.jsdelivr.net/gh/urielch/react-icons-ai@1.0.8/ico/",
```

```ts
export { AiFillEdit } from "react-icons-ai/AiFillEdit";
```

```
error: Expected a JavaScript or TypeScript module, but identified a Unknown module. Importing these types of modules is currently not supported.
  Specifier: https://cdn.jsdelivr.net/gh/urielch/react-icons-fi@1.0.8/ico/
```

Here are the changes I made in a new branch: https://github.com/J053Fabi0/Ayn-Rand-Frases-Bot-Telegram/commit/fdde26008f41c83f94ae9714087b35c974ac3a19

**Comment by J053Fabi0** [comment]
I see my problem, I'm missing the `.ts` extension. Hold on...

**Comment by J053Fabi0** [comment]
# After changes 327 kB [test-alternative-icon-integration](https://github.com/J053Fabi0/Ayn-Rand-Frases-Bot-Telegram/compare/test-alternative-icon-integration)
![image](https://github.com/J053Fabi0/Ayn-Rand-Frases-Bot-Telegram/assets/12930717/22fc8115-2b94-4a5e-ac0f-748803e5fb36)

# No changes 327 kB [desp.ts](https://github.com/J053Fabi0/Ayn-Rand-Frases-Bot-Telegram/blob/main/deps.ts) - [import_map.json](https://github.com/J053Fabi0/Ayn-Rand-Frases-Bot-Telegram/blob/main/import_map.json)
![image](https://github.com/J053Fabi0/Ayn-Rand-Frases-Bot-Telegram/assets/12930717/6273715f-94ea-48f2-bd96-01040086aa40)

I ran a hard-reload no both tests: ctrl + shift + r. I'm using vivaldi.

**Comment by J053Fabi0** [comment]
I tested it using the Deno Deploy service, and it's still is the same size.

**Comment by UrielCh** [comment]
thx for testing.
